pipeline {

  environment {
     registry = "atos06/monappliweb"
     registryCredential = 'docker-hub-credentials'
     dockerImage = ''
  }

  agent any
  
  stages {

    stage('Build de l application') {
      steps {
        script {
           dockerImage = docker.build(registry + ":$BUILD_NUMBER","./application")
        }
      }
    }

    stage('Tests') {
      parallel {

        stage('Test affichage de la page d accueil') {
          steps {
            script {
               docker.image(registry+":$BUILD_NUMBER").withRun('--rm -p 80:80 --name devops') { c ->
                  sh 'docker ps'
                  sh 'docker exec devops curl localhost:80'
                  sh 'echo "Tests passed"'
               }
            }
          }
        }

        stage('Test fonctionnel') {
          steps {
            script {
              sh 'sleep 5'
            }
          }
        }

      }
    }

    stage('Livraison de la release (Artefact)') {
       steps{
          script {
             docker.withRegistry('https://registry.hub.docker.com', registryCredential ) {
                dockerImage.push("1.0")
             }
          }
       }
    }

     stage('Déploiement de la release en production') {
       steps{
          script {
            def dockerRun = 'sudo docker stop monserver;sudo docker rm monserver;sudo docker rmi '+registry+':1.0;sudo docker run -d --name monserver -p 8081:80 '+registry+':1.0'
            
            sh """ssh -vvv -tt -o StrictHostKeyChecking=no ubuntu@ec2-3-78-65-164.eu-central-1.compute.amazonaws.com << EOF
            ${dockerRun}
            exit
            EOF""" 
          }
       }
    }
    
  }
}
